parameters:
    bbapp.rest.listener_exception.mapping:
        Exception:
            code: 500
        Symfony\Component\Security\Core\Exception\ProviderNotFoundException:
            code: 401
            message: Authentication failed - supplied public key or signature is incorrect
        Doctrine\ORM\ORMException:
            code: 500
        Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException:
            code: 401
            message: Authenticaton failed - public key not provided

services:
    rest.hydrator:
        class: BackBee\Rest\Hydration\RestHydrator
        arguments: [ "@em" ]

    rest.encoder_provider:
        class: BackBee\Rest\Encoder\ContainerEncoderProvider
        calls:
            - [ setContainer, [ '@service_container' ] ]
        arguments: [ { json: "rest.encoder.json", xml: "rest.encoder.xml" } ]

    rest.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    rest.encoder.xml:
        class: Symfony\Component\Serializer\Encoder\XmlEncoder

    rest.listener.body:
        class: BackBee\Rest\EventListener\BodyListener
        arguments: [ '@rest.encoder_provider', true ]
        calls:
            - [ setPath, [ '%bbapp.rest_api.path%' ] ]

    rest.listener.exception:
        class: BackBee\Rest\EventListener\ExceptionListener
        calls:
            - [ setPath, [ '%bbapp.rest_api.path%' ] ]
            - [ setMapping, [ '%bbapp.rest.listener_exception.mapping%' ] ]

    rest.listener.validation:
        class: BackBee\Rest\EventListener\ValidationListener
        arguments: [ '@service_container' ]

    rest.listener.pagination:
        class: BackBee\Rest\EventListener\PaginationListener
        arguments: [ '@rest.metadata.factory', '@validator' ]
        calls:
            - [ setPath, [ '%bbapp.rest_api.path%' ] ]

    rest.listener.param_converter:
        class: BackBee\Rest\EventListener\ParamConverterListener
        arguments: [ '@rest.metadata.factory', '@validator' ]
        calls:
            - [ setPath, [ '%bbapp.rest_api.path%' ] ]

    rest.listener.security:
        class: BackBee\Rest\EventListener\SecurityListener
        arguments: [ '@security.context', '@bb.expression_language', '@security.trust_resolver', '@security.role_hierarchy' ]
        calls:
            - [ setMetadataFactory, [ '@rest.metadata.factory' ] ]

    rest.metadata.annotation_reader:
        class: Doctrine\Common\Annotations\AnnotationReader

    rest.metadata.annotation_driver:
        class: BackBee\Rest\Mapping\Driver\AnnotationDriver
        arguments: [ '@rest.metadata.annotation_reader' ]

    rest.metadata.factory:
        class: Metadata\MetadataFactory
        arguments: [ '@rest.metadata.annotation_driver' ]
        calls:
            - [ setCache, [ '@rest.metadata.cache' ] ]

    rest.metadata.cache:
        class: BackBee\Rest\Metadata\Cache\BackBeeCache
        arguments: [ '@cache.bootstrap', '%debug%' ]
