# renderer configuration

bb_scripts_directory:
    common: %bbapp.base.dir%/Resources/scripts

adapter:
    twig:
        class: BackBee\Renderer\Adapter\Twig
        config:
            enable_autoreload: true
            enable_cache: true
            cache_dir: ~
    phtml:
        class: BackBee\Renderer\Adapter\phtml
        config: []

path:
    scriptdir: Templates/scripts
    layoutdir: Layouts
